# Generated by Django 3.0.7 on 2020-06-09 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название товара')),
                ('image', models.ImageField(blank=True, upload_to='shop/', verbose_name='Изображения')),
                ('description', models.TextField(verbose_name='Описание')),
                ('character', models.CharField(max_length=300, verbose_name='Характеристика')),
                ('pub_date', models.DateTimeField(default='', verbose_name='Дата публикации')),
                ('price', models.CharField(max_length=100, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default='', verbose_name='Дата публикации')),
                ('author_name', models.CharField(max_length=60, verbose_name='Имя автора')),
                ('comment_text', models.TextField(verbose_name='Текст комментария')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Products')),
            ],
            options={
                'verbose_name': 'Комментария',
                'verbose_name_plural': 'Комментарий',
            },
        ),
    ]
